### PR TITLE
Account Creation Extra Fields

### PR DESCRIPTION
**Pull request by Ledoux**
given #31 

screen shot 2017-10-18 at 22 27 30

### CODE REVIEW

**Comment by Ledoux** [comment]
@Atala actually, I don't know if I need to go deeper here...

do we want some input mask (like https://www.npmjs.com/package/react-bootstrap-maskedinput) for the phone number?

**Comment by Ledoux** [comment]
BTW, I know that my register can throw an error because of this typically:

screen shot 2017-10-18 at 23 08 20

have we got a way to display frontend the error of already existing email and username?

**Comment by Atala** [comment]
I think it would be very nice if you could add error display.

I don't think we need to bother with a mask for now on, what we (I) should do is to add phone number validation on the backend side, and then enforce it with a mask.

**Comment by alexsegura** [comment]
Still not good?

May I rebase and merge?

**Comment by Atala** [comment]
@Ledoux do you have time to add a simple error-display mechanism?

**Comment by Atala** [comment]
@Ledoux the 500 error on user creation is actually a shame, I will fix it for proper error message / 400.

**Comment by Ledoux** [comment]
@Atala 
ok cool, 

this banch is rebased, and I propose to merge it.

The feature of handling the error from the backend request will be done in another self-dedicated pr:).

**Pull request merged**
